name: taskordersrate
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  fluttertoast: ^8.2.12
  logger: ^2.6.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  go_router: ^15.2.4
  flutter_screenutil: ^5.9.3
  loader_overlay: ^5.0.0
  curved_navigation_bar: ^1.0.6
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/
    

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 